language: generic
os: linux
python: 3.6

jobs:
  include:
  - name: TOXENV=lint
    script: tox -v -e lint
  - name: py36-test
    script: tox -v
  - name: TOXENV=mypy
    script: tox -v -e mypy
  - name: TOXENV=env-check
    script: tox -v -e env-check

before_install:
  - env
  - pyenv versions
  - pyenv local 3.6.7
  - pip --version
  - python3.6 -m venv venv
  - source venv/bin/activate


install:
  - pip install -U pip setuptools
  - pip install tox
  - pip freeze

notifications:
  email: false
